apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rose-app-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rose-app-dep
  minReplicas: 2
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20
