trigger:
- none

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: deploy_dev
    displayName: 'Deploy in dev env'
    variables: 
    - group: aks-deploy-dev
    jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'iveetechgeekready2021-dev.geekready2021'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: deploy-aks-app.steps.yml
              parameters:
                dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
                imagePullSecret: '$(imagePullSecret)'
                containerRegistry: '$(containerRegistry)'
                imageRepository: '$(imageRepository)'
                imageTag: '$(imageTag)'
  - stage: deploy_test
    displayName: 'Deploy in test env'
    dependsOn: deploy_dev
    variables: 
    - group: aks-deploy-test
    jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'iveetechgeekready2021-test.geekready2021'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: deploy-aks-app.steps.yml
              parameters:
                dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
                imagePullSecret: '$(imagePullSecret)'
                containerRegistry: '$(containerRegistry)'
                imageRepository: '$(imageRepository)'
                imageTag: '$(imageTag)'
