trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.6.3'
    installKubectl: true
    kubectlVersion: '1.22.1'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Visual Studio Enterprise Subscription(62755989-1bb3-4d7b-8131-13e79f4bdc5f)'
    azureResourceGroup: 'zz-dev'
    kubernetesCluster: 'zz-dev-aks'
    namespace: 'geekready2021'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: './src/rose/rose-app-chart/'
    valueFile: './src/rose/rose-app-chart/values.yaml'
    waitForExecution: false
    install: true
    useClusterAdmin: true

