trigger:
  none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    az bicep build -f src/infra/aks/main.bicep
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'VSE'
    subscriptionId: '***'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'zz-test'
    location: 'Australia Central'
    templateLocation: 'Linked artifact'
    csmFile: 'src/infra/aks/main.json'
    csmParametersFile: 'src/infra/aks/parameters_test.json'
    deploymentMode: 'Incremental'
